# Generated by Django 4.2.28 on 2026-02-09 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('profession', models.CharField(choices=[('etudiant', 'Étudiant'), ('salarie_junior', 'Salarié Junior (< 2 ans)'), ('salarie_confirme', 'Salarié Confirmé (2-5 ans)'), ('salarie_senior', 'Salarié Senior (> 5 ans)'), ('entrepreneur', 'Entrepreneur'), ('retraite', 'Retraité'), ('entreprise', 'Entreprise')], max_length=30)),
                ('revenu_mensuel', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenu mensuel (FCFA)')),
                ('charges_mensuelles', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Charges mensuelles (FCFA)')),
                ('dettes_existantes', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dettes mensuelles existantes (FCFA)')),
                ('anciennete_emploi', models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancienneté emploi (années)')),
                ('incidents_paiement', models.PositiveIntegerField(default=0, verbose_name='Incidents de paiement (12 derniers mois)')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('numero_registre_commerce', models.CharField(blank=True, max_length=50, verbose_name='N° Registre Commerce')),
                ('secteur_activite', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('chiffre_affaires_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires annuel (FCFA)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
                'permissions': [('view_own_client', 'Peut voir ses propres clients'), ('view_all_clients', 'Peut voir tous les clients')],
            },
        ),
        migrations.CreateModel(
            name='DossierPret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence dossier')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Montant demandé (FCFA)')),
                ('duree_mois', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Durée (mois)')),
                ('objet_pret', models.CharField(choices=[('personnel', 'Prêt Personnel'), ('immobilier', 'Prêt Immobilier'), ('vehicule', 'Prêt Véhicule'), ('education', 'Prêt Éducation'), ('commerce', 'Prêt Commercial'), ('agricole', 'Prêt Agricole'), ('equipement', 'Prêt Équipement'), ('autre', 'Autre')], max_length=20, verbose_name='Objet du prêt')),
                ('apport_personnel', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Apport personnel (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description / Justification')),
                ('etat', models.CharField(choices=[('soumis', 'Soumis'), ('en_analyse', 'En Analyse'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('alerte_fraude', 'Alerte Fraude')], default='soumis', max_length=20, verbose_name='État du dossier')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_analyse', models.DateTimeField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('motif_decision', models.TextField(blank=True, verbose_name='Motif de la décision')),
                ('score_risque', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Score de risque')),
                ('niveau_risque', models.CharField(blank=True, max_length=30, verbose_name='Niveau de risque')),
                ('recommandation', models.TextField(blank=True, verbose_name='Recommandation du système')),
                ('alerte_fraude', models.BooleanField(default=False, verbose_name='Alerte fraude')),
                ('details_scoring', models.JSONField(blank=True, null=True, verbose_name='Détails du scoring')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='dossiers.client')),
                ('conseiller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_geres', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller')),
            ],
            options={
                'verbose_name': 'Dossier de prêt',
                'verbose_name_plural': 'Dossiers de prêt',
                'ordering': ['-date_soumission'],
                'permissions': [('view_own_dossier', 'Peut voir ses propres dossiers'), ('view_all_dossiers', 'Peut voir tous les dossiers'), ('change_etat_dossier', "Peut changer l'état d'un dossier"), ('generate_pdf_dossier', 'Peut générer le PDF du dossier')],
            },
        ),
        migrations.CreateModel(
            name='ResultatScoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_global', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score_endettement', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score_historique', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score_stabilite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score_coherence', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ratio_endettement', models.DecimalField(decimal_places=4, max_digits=6)),
                ('niveau_risque', models.CharField(max_length=30)),
                ('recommandation', models.TextField()),
                ('alerte_fraude', models.BooleanField(default=False)),
                ('alertes', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('calcule_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_scoring', to='dossiers.dossierpret')),
            ],
            options={
                'verbose_name': 'Résultat de scoring',
                'verbose_name_plural': 'Résultats de scoring',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_piece', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('bulletin_salaire', 'Bulletin de salaire'), ('releve_bancaire', 'Relevé bancaire'), ('attestation_travail', 'Attestation de travail'), ('registre_commerce', 'Registre de commerce'), ('bilan', 'Bilan comptable'), ('facture_proforma', 'Facture proforma'), ('titre_foncier', 'Titre foncier'), ('autre', 'Autre document')], max_length=30, verbose_name='Type de pièce')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('fichier', models.FileField(upload_to='pieces_justificatives/%Y/%m/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='dossiers.dossierpret')),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
            },
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_compte', models.CharField(max_length=30, unique=True, verbose_name='Numéro de compte')),
                ('type_compte', models.CharField(choices=[('epargne', 'Épargne'), ('courant', 'Courant'), ('professionnel', 'Professionnel')], max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde (FCFA)')),
                ('date_ouverture', models.DateField(verbose_name="Date d'ouverture")),
                ('est_actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='dossiers.client')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('changement_etat', "Changement d'état"), ('calcul_score', 'Calcul de score'), ('modification_score', 'Modification de score'), ('upload_piece', 'Upload de pièce'), ('generation_pdf', 'Génération PDF'), ('suppression', 'Suppression')], max_length=30)),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle concerné')),
                ('objet_id', models.CharField(max_length=50, verbose_name="ID de l'objet")),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('donnees_avant', models.JSONField(blank=True, null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, null=True, verbose_name='Données après modification')),
                ('raison', models.TextField(blank=True, verbose_name='Raison / Justification')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_action'],
            },
        ),
    ]
