# Generated by Django 4.2.28 on 2026-02-09 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'agence")),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code agence')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences_gerees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° CNI'),
        ),
        migrations.AddField(
            model_name='dossierpret',
            name='explication_score',
            field=models.TextField(blank=True, verbose_name='Explication du score (IA)'),
        ),
        migrations.AddField(
            model_name='dossierpret',
            name='score_fraude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Score de fraude'),
        ),
        migrations.AddField(
            model_name='resultatscoring',
            name='explication',
            field=models.TextField(blank=True, verbose_name='Explication IA du score'),
        ),
        migrations.AddField(
            model_name='resultatscoring',
            name='score_fraude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('changement_etat', "Changement d'état"), ('calcul_score', 'Calcul de score'), ('modification_score', 'Modification de score'), ('upload_piece', 'Upload de pièce'), ('generation_pdf', 'Génération PDF'), ('export_donnees', 'Export de données'), ('suppression', 'Suppression'), ('notification', 'Notification envoyée')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('conseiller', 'Conseiller'), ('manager_risque', 'Manager Risque'), ('admin', 'Administrateur'), ('auditeur', 'Auditeur')], default='conseiller', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='dossiers.agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Alerte')], default='info', max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('lue', models.BooleanField(default=False)),
                ('envoyee_email', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='dossiers.agence'),
        ),
    ]
