# Generated by Django 4.2.28 on 2026-02-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_agence_client_numero_cni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('conseiller', 'Conseiller Clientèle'), ('gestionnaire', 'Gestionnaire de Compte'), ('manager_risque', 'Manager Risque'), ('admin', 'Administrateur')], default='conseiller', max_length=20),
        ),
    ]
